# Generated by Django 3.2.5 on 2021-07-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profilePicture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
