# Generated by Django 3.2.5 on 2021-07-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kid', '0003_alter_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(null=True, upload_to='')),
                ('imgId', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='blogId',
            field=models.IntegerField(null=True),
        ),
    ]
