# Generated by Django 3.2.6 on 2021-08-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kid', '0005_gallery_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255, null=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
